### PR TITLE
Add PythonFileDigest to schema documentation

### PR DESCRIPTION
**Pull request by fridex**

### CODE REVIEW

**Comment by fridex** [comment]
@bissenbay looking at the changes, it might be better to name edge "FoundFile" instead of "FileFound" (verb).

@pacospace WDYT?

**Comment by bissenbay** [comment]
There is a typo on docs/schema.png. ```file_cound``` needs to be changed to ```file_found```

**Comment by fridex** [comment]
> There is a typo on docs/schema.png. `file_cound` needs to be changed to `file_found`

Nice catch! I adjusted it to "found_file". Let's wait for @pacospace opinion on edge naming.

**Comment by pacospace** [comment]
I agree with @fridex for the edge. I would use singular for the name of the node because there is a single hash. Otherwise LGTM! :+1:

**Pull request merged**
