### PR TITLE
Use open instead of pathlib to adress PV in-cluster issues

### PR DESCRIPTION
**Pull request by fridex**

### CODE REVIEW

**Comment by fridex** [comment]
recheck

**Comment by pacospace** [comment]
recheck

**Comment by goern** [comment]
recheck

**Comment by goern** [comment]
regate

**Comment by goern** [comment]
why is the pytest taking longer than 5min?! I think the root cause for the pytest failure is a timeout between Zuul and OpenShift Pod

**Comment by goern** [comment]
regate

**Pull request merged**
