### PR TITLE
Fix migration creating indexes

### PR DESCRIPTION
**Pull request by fridex**
Index depends_on_entity_id_idx is created in `a7442899ef28_add_indexes_needed_for_revsolver.py`.
Index depends_on_version_id_idx is created in `79e1d320db3d_create_index_for_get_depends_on_query.py`.

## Related Issues and Dependencies

Fixes: #1817

## This introduces a breaking change

- [ ] Yes
- [x] No

## This should yield a new module release

- [x] Yes
- [ ] No

### CODE REVIEW

**Comment by harshad16** [comment]
@fridex , we would have to relock the dependencies
feels like botocore 1.17.1 
package sha has mismatch https://pypi.org/project/botocore/1.17.1/#copy-hash-modal-3313d8e0-6016-42e5-b501-3045476ca1e7 
https://github.com/thoth-station/storages/blob/27de632c70a97295e5105e001e94dda6c076cd43/Pipfile.lock#L97
causing pytest to fail.

**Comment by fridex** [comment]
recheck

**Comment by fridex** [comment]
recheck

**Comment by harshad16** [comment]
> recheck

@fridex , feels like zuul is observe issue on running pytest. we can use `/approve` for to merge this with aicoe-ci. i will look into this behaviour of zuul more.

**Pull request merged**
