### PR TITLE
Extend Python package index with only_packages_seen attribute

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Related: https://github.com/thoth-station/thoth-application/issues/1822

## This introduces a breaking change

- [x] No

### CODE REVIEW

**Comment by fridex** [comment]
It would be great to have this reviewed and changes released. The current master branch of management-api is broken as it required this change in first.

**Review by pacospace — APPROVED** [review]
lgtm! 💯

**Comment by pacospace** [comment]
@fridex PTAL at pre-commit

**Pull request merged**
