### PR TITLE
Allow nullable software environemnts in the schema

### PR DESCRIPTION
**Pull request by fridex**
Do not treat foreign keys as primary keys.

Fixes: #1122

### CODE REVIEW

**Comment by fridex** [comment]
@pacospace please pull and test if it fixes the issue

**Comment by pacospace** [comment]
```
Revision ID: de4ef92827aa
Revises: e05d6d95ea95
Create Date: 2019-10-21 08:57:56.953605+00:00
Traceback (most recent call last):
  File "/home/fmurdaca/.local/share/virtualenvs/storages-kD6ztVxe/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "/home/fmurdaca/.local/share/virtualenvs/storages-kD6ztVxe/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 580, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.InvalidTableDefinition: column "software_environment_id" is in a primary key
```

**Comment by fridex** [comment]
@pacospace what alembic version do you use?

```
$ pipenv run python3 -c "import alembic; print(alembic.__version__)"
1.2.1
```

I cannot reproduce this issue.

**Comment by pacospace** [comment]
> @pacospace what alembic version do you use?
> 
> ```
> $ pipenv run python3 -c "import alembic; print(alembic.__version__)"
> 1.2.1
> ```
> 
> I cannot reproduce this issue.

Same:

```
pipenv run python3 -c "import alembic; print(alembic.__version__)"
1.2.1
```

**Comment by fridex** [comment]
> > @pacospace what alembic version do you use?
> > ```
> > $ pipenv run python3 -c "import alembic; print(alembic.__version__)"
> > 1.2.1
> > ```
> > 
> > 
> > I cannot reproduce this issue.
> 
> Same:
> 
> ```
> pipenv run python3 -c "import alembic; print(alembic.__version__)"
> 1.2.1
> ```

OK, it seems like we accidentally started using composite primary keys. Please take a look again, I've updated the migration.

**Pull request merged**
