### PR TITLE
Modify data type for metadata keys: Str -> Text

### PR DESCRIPTION
**Pull request by pacospace**
Fixes: https://github.com/thoth-station/storages/issues/1291
Fixes: https://github.com/thoth-station/storages/issues/1294
Fixes: https://github.com/thoth-station/storages/issues/1296
Fixes: https://github.com/thoth-station/storages/issues/1320
Fixes: https://github.com/thoth-station/storages/issues/1322
Fixes: https://github.com/thoth-station/storages/issues/1323

Signed-off-by: Francesco Murdaca <fmurdaca@redhat.com>

### CODE REVIEW

**Comment by pacospace** [comment]
> What about using `Text` as its done in warehouse implementation? This way we will keep increasing forever
> 
> [#1323 (comment)](https://github.com/thoth-station/storages/issues/1323#issuecomment-557934189)

I was going to ask you that indeed :) Definetly better solution. Thanks!

**Comment by pacospace** [comment]
Apparently also with the flag `compare_type = True` alembic is not able to find changes in datatype between String and Text (in character length yes). I will adjust the migration manually.

**Comment by pacospace** [comment]
> Apparently also with the flag `compare_type = True` alembic is not able to find changes in datatype between String and Text. I will adjust the migration manually.

Please Test it as well, otherwise should we open issue in `alembic` project?

**Comment by fridex** [comment]
> > Apparently also with the flag `compare_type = True` alembic is not able to find changes in datatype between String and Text. I will adjust the migration manually.
> 
> Please Test it as well, otherwise should we open issue in `alembic` project?

Awesome :+1: Will test it. And it might be worth to discuss this upstream.

**Comment by pacospace** [comment]
recheck

**Comment by pacospace** [comment]
recheck

**Pull request merged**
