### PR TITLE
Use common datetime parsing handling

### PR DESCRIPTION
**Pull request by fridex**

### CODE REVIEW

**Comment by fridex** [comment]
Needs proper testing.

**Comment by goern** [comment]
@fridex can you provide some test cases?

**Comment by fridex** [comment]
> @fridex can you provide some test cases?

Rebased, this change should be already covered by tests:

https://github.com/thoth-station/storages/blob/cd22dda2761b1ffd34d2d41871a69077e15237bb/tests/test_result_schema.py#L70-L72

**Pull request merged**
