### PR TITLE
Provide a method for deleting index

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Related: https://github.com/thoth-station/management-api/issues/790

## This introduces a breaking change

- [x] No

### CODE REVIEW

**Review by harshad16 — COMMENTED** [review]
/lgtm
:+1: 
/test all

**Comment by pacospace** [comment]
@fridex wdyt about https://github.com/thoth-station/storages/issues/2385?

**Comment by pacospace** [comment]
@fridex please take care of pre-commit :)

**Review by pacospace — APPROVED** [review]
Lgtm! thanks!!

**Pull request merged**
