### PR TITLE
Fixes: Mypy + pre-commit config

### PR DESCRIPTION
**Pull request by VannTen**
- Update + fix pre-commit config
- Fix flake8 pre-commit hooks
- Fix mypy configuration
- Apply https://github.com/hauntsaninja/no_implicit_optional
- Fix mypy errors

### CODE REVIEW

**Review by mayaCostantini — APPROVED** [review]
/lgtm thanks :+1:

**Comment by VannTen** [comment]
Looks like LSP renaming does not work super well :/

**Comment by VannTen** [comment]
> /lgtm thanks +1

lgtm label apparently was not added. Might need to be on a line by itself, unless prow has a bug.

**Pull request merged**
