### PR TITLE
using thoth-pytest job

### PR DESCRIPTION
**Pull request by goern**
Depends-On: https://github.com/thoth-station/zuul-test-jobs/pull/12

### CODE REVIEW

**Comment by goern** [comment]
recheck

**Comment by goern** [comment]
recheck

**Comment by goern** [comment]
recheck

**Comment by goern** [comment]
recheck

**Comment by goern** [comment]
recheck

**Comment by TristanCacqueray** [comment]
recheck

**Comment by goern** [comment]
@fridex please have a look at the python tests ;)

**Comment by goern** [comment]
recheck

**Comment by goern** [comment]
recheck

**Pull request merged**
