### PR TITLE
Provide methods for deleting data from the database

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Related: https://github.com/thoth-station/thoth-application/issues/808

## This introduces a breaking change

- [x] No

### CODE REVIEW

**Comment by fridex** [comment]
@pacospace PTAL I tested the queries locally, but extra pair of eyes when deleting data are always valuable 🔢  👓 👀

**Review by pacospace — COMMENTED** [review]
lgtm! 💯 one question regarding deletion, for example for solver, are the data deleting also relationships? like package version and pacakge version for a solver?

**Comment by fridex** [comment]
> lgtm!  one question regarding deletion, for example for solver, are the data deleting also relationships? like package version and pacakge version for a solver?

Yes, they should be - we have `ondelete="CASCADE"` all over the place (tried it locally). But worth to make a dump before trying these operations in a deployment.

**Review by pacospace — APPROVED** [review]
Thanks 💯 👀 did not spot anything, but it is also friday 🍻

**Pull request merged**
