### PR TITLE
Do not sync package errors if the given package is not provided

### PR DESCRIPTION
**Pull request by fridex**

### CODE REVIEW

**Comment by fridex** [comment]
Schema needs to be adjusted.

**Comment by fridex** [comment]
Hm... two cases actually:

1. when there is no package with the given name:

https://github.com/thoth-station/solver/blob/f173726cce57864e4661236b72ef2d4ba3674d6a/thoth/solver/python/python.py#L313

1. There is a package with the given name, but the given version does not exist:

https://github.com/thoth-station/solver/blob/f173726cce57864e4661236b72ef2d4ba3674d6a/thoth/solver/python/python.py#L356

@pacospace @goern do we want to introduce `is_package_provided` and `is_version_provided`?

**Comment by pacospace** [comment]
This case shouldn't be considered? because from unsolved there will be created a package that is not on that index. WDYT?

```
{
  "metadata": {
    "analyzer": "thoth-solver",
    "analyzer_version": "1.3.0",
    "arguments": {
      "python": {
        "exclude_packages": null,
        "index": "https://pypi.org/simple,https://tensorflow.pypi.thoth-station.ninja/index/manylinux2010/AVX2/simple",
        "no_pretty": false,
        "no_transitive": true,
        "output": "http://result-api/api/v1/solver-result",
        "requirements": "setuptools==12.0.1"
      },
      "thoth-solver": {
        "verbose": false
      }
    },
    "datetime": "2019-10-31T14:06:20.055370",
    "distribution": {
      "codename": "Ootpa",
      "id": "rhel",
      "like": "fedora",
      "version": "8.0",
      "version_parts": {
        "build_number": "",
        "major": "8",
        "minor": "0"
      }
    },
    "duration": 11,
    "hostname": "solver-rhel-8.0-py36-250b8edb6d7e3af9-wpt76",
    "python": {
      "api_version": 1013,
      "implementation_name": "cpython",
      "major": 3,
      "micro": 8,
      "minor": 6,
      "releaselevel": "final",
      "serial": 0
    },
    "timestamp": 1572530780
  },
  "result": {
    "environment": {
      "implementation_name": "cpython",
      "implementation_version": "3.6.8",
      "os_name": "posix",
      "platform_machine": "x86_64",
      "platform_python_implementation": "CPython",
      "platform_release": "3.10.0-957.21.2.el7.x86_64",
      "platform_system": "Linux",
      "platform_version": "#1 SMP Tue May 28 09:26:43 UTC 2019",
      "python_full_version": "3.6.8",
      "python_version": "3.6",
      "sys_platform": "linux"
    },
    "environment_packages": [
      {
        "package_name": "pipdeptree",
        "package_version": "0.13.2"
      }
    ],
    "errors": [
      {
        "details": {
          "message": "Failed to successfully execute function in Python interpreter: Traceback (most recent call last):\n  File \"<string>\", line 21, in <module>\n  File \"<string>\", line 8, in _find_distribution_name\n  File \"/home/solver/venv/lib/python3.6/site-packages/pkg_resources/__init__.py\", line 1696, in <module>\n    register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)\nAttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'\n"
        },
        "index_url": "https://pypi.org/simple",
        "is_provided": true,
        "package_name": "setuptools",
        "package_version": "12.0.1",
        "type": "command_error"
      }
    ],
    "tree": [],
    "unparsed": [],
    "unresolved": [
      {
        "index_url": "https://tensorflow.pypi.thoth-station.ninja/index/manylinux2010/AVX2/simple",
        "package_name": "setuptools",
        "version_spec": "==12.0.1"
      }
    ]
  }
}
```

**Comment by goern** [comment]
@fridex @pacospace is this good to merge?

**Comment by fridex** [comment]
As discussed, introduced `is_provided_package` and `is_provided_package_version` flags that distinguish scenarios of solver errors in https://github.com/thoth-station/solver/pull/401.

**Pull request merged**
