### PR TITLE
Fix software_environment_id null violation

### PR DESCRIPTION
**Pull request by harshad16**
Fix software_environment_id null violation
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>

## Related Issues and Dependencies

Related-to: https://github.com/thoth-station/storages/issues/2745

## This should yield a new module release

- [x] Yes
- [ ] No

## Description

Mentioned the details: https://github.com/thoth-station/storages/issues/2745#issuecomment-1377780752

### CODE REVIEW

**Review by mayaCostantini — APPROVED** [review]
lgtm, thanks!

**Comment by harshad16** [comment]
Thanks all for the review
Merging for the release

**Pull request merged**
