### PR TITLE
Drop id columns on relation tables

### PR DESCRIPTION
**Pull request by fridex**
... to reduce footprint, cache size and limits for large tables (e.g. 
depends_on) which could easily overflow given the size of our database and
with the current id datatype used.

Fixes: #1437

Depends-On: #1456

### CODE REVIEW

**Comment by fridex** [comment]
I've run a few tests not to corrupt our database. @pacospace could you please double-check that everything is ok? In the worst case, we still have backups. Thanks! :+1:

**Comment by pacospace** [comment]
> I've run a few tests not to corrupt our database. @pacospace could you please double-check that everything is ok? In the worst case, we still have backups. Thanks!

I checked for queries that rely on those properties and I identified:
- `has_python_solver_error`
- `get_relation_table_count`

**Comment by fridex** [comment]
> There are two queries affected

I'm not sure if I follow. Does it mean these two queries failed/

**Comment by pacospace** [comment]
> > There are two queries affected
> 
> I'm not sure if I follow. Does it mean these two queries failed/

Yes if we remove the `id` from relation tables, those two queries are affected.

**Comment by fridex** [comment]
> > > There are two queries affected
> > 
> > 
> > I'm not sure if I follow. Does it mean these two queries failed/
> 
> Yes if we remove the `id` from relation tables, those two queries are affected.

66efe72 addresses `get_relation_table_count`

**Comment by fridex** [comment]
`1b7dab5` addresses `has_python_solver_error`. I think we don't need explicit order here.

**Comment by fridex** [comment]
> `1b7dab5` addresses `has_python_solver_error`. I think we don't need explicit order here.

Hm, actually we do to take into account the most recent solver. Adjusted in 0078b5c. PTAL and thanks for testing!

**Comment by fridex** [comment]
To make sure we do not corrupt/lose any data, I've created a backup in stage environment. The backup is available on Ceph - object key prefix is `data/thoth/thoth-psi-stage/graph-backup/pg_dump-20-01-08-16-57-52`.

**Pull request merged**
