### PR TITLE
fix iter dates method

### PR DESCRIPTION
**Pull request by pacospace**
Signed-off-by: Francesco Murdaca <fmurdaca@redhat.com>

### CODE REVIEW

**Review by fridex — APPROVED** [review]
nice catch 👍🏻

**Comment by fridex** [comment]
Wait... What is the intention here? The original code looks correct to me - if there is no `end_date` date supplied, today+1 is considered as the `end_date`.

**Comment by pacospace** [comment]
> Wait... What is the intention here? The original code looks correct to me - if there is no `end_date` date supplied, today+1 is considered as the `end_date`.

How do I take the data of the same date? for example 2021-february-26. Either we modify that line or there is a bug when `start_date == end_date`, no data are collected, unless we modify `while walker <= end_date`

**Comment by fridex** [comment]
The following code should give back all the results starting year 2021 to this date:

```python
adapter.iterate_results(start_date=date(year=2021, month=1, day=1), end_date=None)
```

With the patch applied it would get back only results for this equivalent call:

```python
adapter.iterate_results(start_date=date(year=2021, month=1, day=1), end_date=date(year=2021, month=1, day=2))
```

**Comment by pacospace** [comment]
> The following code should give back all the results starting year 2021 to this date:
> 
> ```python
> adapter.iterate_results(start_date=date(year=2021, month=1, day=1), end_date=None)
> ```
> 
> With the patch applied it would get back only results for this equivalent call:
> 
> ```python
> adapter.iterate_results(start_date=date(year=2021, month=1, day=1), end_date=date(year=2021, month=1, day=2))
> ```
what about `start_date == end_date`?

**Comment by fridex** [comment]
> > Wait... What is the intention here? The original code looks correct to me - if there is no `end_date` date supplied, today+1 is considered as the `end_date`.
> 
> How do I take the data of the same date? for example 2021-february-26:

The `end_date` is not inclusive:

```python
adapter.iterate_results(start_date=date(year=2021, month=2, day=26), end_date=date(year=2021, month=2, day=27))
```

Reads as "get results starting 2021-02-26 till 2021-02-27".

**Comment by pacospace** [comment]
> > > Wait... What is the intention here? The original code looks correct to me - if there is no `end_date` date supplied, today+1 is considered as the `end_date`.
> > 
> > 
> > How do I take the data of the same date? for example 2021-february-26:
> 
> The `end_date` is not inclusive:
> 
> ```python
> adapter.iterate_results(start_date=date(year=2021, month=2, day=26), end_date=date(year=2021, month=2, day=27))
> ```
> 
> Reads as "get results starting 2021-02-26 till 2021-02-27".

So it is expected to give no results if start_date == end_date? I would add a condition then when they are equal to fall back to the case you just described, wdyt?

**Comment by pacospace** [comment]
> > > > Wait... What is the intention here? The original code looks correct to me - if there is no `end_date` date supplied, today+1 is considered as the `end_date`.
> > > 
> > > 
> > > How do I take the data of the same date? for example 2021-february-26:
> > 
> > 
> > The `end_date` is not inclusive:
> > ```python
> > adapter.iterate_results(start_date=date(year=2021, month=2, day=26), end_date=date(year=2021, month=2, day=27))
> > ```
> > 
> > 
> > Reads as "get results starting 2021-02-26 till 2021-02-27".
> 
> So it is expected to give no results if `start_date == end_date`? I would add a condition then when they are equal to fall back to the case you just described, wdyt?

added 
```
        elif end_date == start_date:
            end_date = start_date + timedelta(days=1)
```

**Comment by fridex** [comment]
> > So it is expected to give no results if `start_date == end_date`? I would add a condition then when they are equal to fall back to the case you just described, wdyt?
> 
> added
> 
> ```
>         elif end_date == start_date:
>             end_date = start_date + timedelta(days=1)
> ```

I would expect it to behave differently to be consistent. In Python, you get the following range in the standard library:

```pytohn
>>> list(range(0, 5))
[0, 1, 2, 3, 4]
```

**Comment by pacospace** [comment]
> > > So it is expected to give no results if `start_date == end_date`? I would add a condition then when they are equal to fall back to the case you just described, wdyt?
> > 
> > 
> > added
> > ```
> >         elif end_date == start_date:
> >             end_date = start_date + timedelta(days=1)
> > ```
> 
> I would expect it to behave differently to be consistent. In Python, you get the following range in the standard library:
> 
> ```
> >>> list(range(0, 5))
> [0, 1, 2, 3, 4]
> ```

Totally make sense!! Thanks 🍻

**Pull request closed without merging**
