### PR TITLE
Adjust constraint on py38

### PR DESCRIPTION
**Pull request by pacospace**
Signed-off-by: Francesco Murdaca <fmurdaca@redhat.com>

## Related Issues and Dependencies

Fixes: https://github.com/thoth-station/storages/issues/2126

Kebechet update didn't solve the problem: https://github.com/thoth-station/storages/commit/c9c1e469cce7378507d5b54321436c9f8451a5d7

, it was necessary to delete Pipfile.lock and recreate

@fridex @saisankargochhayat @goern @harshad16

### CODE REVIEW

**Review by harshad16 — APPROVED** [review]
lgtm, thanks @pacospace  for the relock :100:

**Comment by pacospace** [comment]
> lgtm, thanks @pacospace for the relock

I thought the bot were doing that job for us :robot: :robot: :robot: :robot: :robot: :robot: :robot: :robot: :robot: :robot:

**Comment by harshad16** [comment]
> I thought the bot were doing that job for us

Every now and then, bot needs a little push. :)

**Comment by pacospace** [comment]
automatic approval missing?

**Comment by harshad16** [comment]
> automatic merging missing?

prow needs some config update.

**Comment by pacospace** [comment]
> > automatic merging missing?
> 
> prow needs some config update.

can I merge this manually for now? We need new thoth-storages and new graph-sync, because all sync are failing at the moment

**Pull request merged**
