### PR TITLE
Fix NULL values considered distinct by Postgres < 15

### PR DESCRIPTION
**Pull request by mayaCostantini**
## Related Issues and Dependencies

Related to https://github.com/thoth-station/storages/issues/2729

## This introduces a breaking change

- No

## This should yield a new module release

- Yes

## This Pull Request implements

Fix NULL values considered as distinct by postgres versions < 15. This would possibly enforce the unique constraint set on package version and avoid duplicate package entries in the database table `PythonPackageVersionEntity`.

### CODE REVIEW

**Comment by mayaCostantini** [comment]
Needs https://github.com/thoth-station/storages/pull/2737 to be merged for tests to pass.

**Comment by VannTen** [comment]
Thanks !
/lgtm

**Comment by VannTen** [comment]
And I can approve here, o/
/approve

**Pull request merged**
