### PR TITLE
Remove parts moved to thoth-common

### PR DESCRIPTION
**Pull request by pacospace**
Signed-off-by: Francesco Murdaca <fmurdaca@redhat.com>

## This introduces a breaking change

- [x] Yes
- [ ] No

## This should yield a new module release

- [x] Yes
- [ ] No

## This Pull Request implements

Remove parts already in thoth-common.

### CODE REVIEW

**Comment by goern** [comment]
recheck

**Comment by fridex** [comment]
recheck

**Comment by fridex** [comment]
regate

**Comment by fridex** [comment]
recheck

**Comment by fridex** [comment]
recheck

**Pull request merged**
