### PR TITLE
add marker file PEP561

### PR DESCRIPTION
**Pull request by KPostOffice**
## Related Issues and Dependencies

…

## This introduces a breaking change

- [ ] Yes
- [ ] No

## This should yield a new module release

- [ ] Yes
- [ ] No

## This Pull Request implements

https://www.python.org/dev/peps/pep-0561/

## Description

It looks like this was meant to be included based on, https://github.com/thoth-station/storages/blob/8448e20488d3e3229b2d553cedd9e803e7149534/setup.py#L88

### CODE REVIEW

**Review by fridex — APPROVED** [review]
Thanks! :+1:

**Comment by fridex** [comment]
@KPostOffice A change in setup.py will be also needed.

**Comment by KPostOffice** [comment]
> @KPostOffice A change in setup.py will be also needed.

https://github.com/thoth-station/storages/blob/8448e20488d3e3229b2d553cedd9e803e7149534/setup.py#L88

I think this is all that is required. It is already present in `setup.py`.

**Comment by fridex** [comment]
> > @KPostOffice A change in setup.py will be also needed.
> 
> https://github.com/thoth-station/storages/blob/8448e20488d3e3229b2d553cedd9e803e7149534/setup.py#L88
> 
> @fridex I think this is all that is required. It is already present in `setup.py`.

I wonder how is it possible we missed it in the package tree then. Thanks!

**Pull request merged**
