### PR TITLE
change err to warning

### PR DESCRIPTION
**Pull request by KPostOffice**
Change error to warning so sentry issues are not created

### CODE REVIEW

**Comment by goern** [comment]
hmm, we require amcheck dont we? So I would leave it as an error and eliminate the root cause of the issue we have seen.

**Comment by KPostOffice** [comment]
This is separate from `amcheck` missing. This command errors when the query fails.

**Comment by fridex** [comment]
> This is separate from `amcheck` missing. This command errors when the query fails.

Is this related to reporting insufficient privileges to run amcheck?

**Comment by KPostOffice** [comment]
@fridex Yeah

**Comment by harshad16** [comment]
This PR can be closed.
The insufficient privilege issue was resolved.
Please review and comment on: https://github.com/thoth-station/storages/issues/2250#issuecomment-801633584

**Comment by fridex** [comment]
> This PR can be closed.

OK, let's close this. This suppresses alerting, if the issue was fixed, the alert will not be fired.

**Pull request closed without merging**
