### PR TITLE
Make package version and package index optional in get_depends_on

### PR DESCRIPTION
**Pull request by fridex**
## This introduces a breaking change

- [x] No

## This should yield a new module release

- [x] No

### CODE REVIEW

**Review by pacospace — APPROVED** [review]
:100:

**Comment by pacospace** [comment]
@harshad16

**Comment by harshad16** [comment]
i think rebase would fix it, the check.
currently, the ci pipeline runs checks based on the pull request, i should check the logic to tmp merge and check.

**Comment by pacospace** [comment]
> i think rebase would fix it, the check.
> currently, the ci pipeline runs checks based on the pull request, i should change the logic to tmp merge and check.

@fridex please rebase

**Pull request merged**
