### PR TITLE
Provide ability to include end_date in the results listing

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Related: https://github.com/thoth-station/storages/pull/2281
Related: https://github.com/thoth-station/storages/pull/2282

## This introduces a breaking change

- [x] No

## This should yield a new module release

- [x] No

## This Pull Request implements

To simplify colling, a user can supply `include_end_date ` which will include the `end_date` in the listing.

### CODE REVIEW

**Comment by fridex** [comment]
@pacospace PTAL, not tested.

**Review by pacospace — APPROVED** [review]
NIce! Thanks!! 🥇

**Comment by pacospace** [comment]
@fridex can you please rebase?

**Comment by fridex** [comment]
Rebased, PTAL.

**Pull request merged**
