### PR TITLE
get_python_package_version_count() query

### PR DESCRIPTION
**Pull request by pacospace**
Signed-off-by: Francesco Murdaca <fmurdaca@redhat.com>

### CODE REVIEW

**Comment by pacospace** [comment]
```get_python_package_versions_count()
[('absl-py', '0.1.10', 'https://pypi.org/simple', 1), ('absl-py', '0.1.11', 'https://pypi.org/simple', 1), ('absl-py', '0.1.12', 'https://pypi.org/simple', 1), ('absl-py', '0.1.13', 'https://pypi.org/simple', 1), ('absl-py', '0.1.6', 'https://pypi.org/simple', 1), ('absl-py', '0.1.7', 'https://pypi.org/simple', 1), ('absl-py', '0.1.8', 'https://pypi.org/simple', 1), ('absl-py', '0.1.9', 'https://pypi.org/simple', 1), ('absl-py', '0.2.0', 'https://pypi.org/simple', 1), ('absl-py', '0.2.1', 'https://pypi.org/simple', 1)]```

**Comment by pacospace** [comment]
What output do we want? @fridex

**Comment by fridex** [comment]
Can we have it as a dict so users can consume it easier?

```
{
('absl-py', '0.1.10', 'https://pypi.org/simple'): 1,
('absl-py', '0.1.11', 'https://pypi.org/simple'): 1,
....
}
```

**Comment by pacospace** [comment]
Everything for Thoth users :) 
```
{('absl-py', '0.1.10', 'https://pypi.org/simple'): 1, ('absl-py', '0.1.11', 'https://pypi.org/simple'): 1, ('absl-py', '0.1.12', 'https://pypi.org/simple'): 1, ('absl-py', '0.1.13', 'https://pypi.org/simple'): 1, ('absl-py', '0.1.6', 'https://pypi.org/simple'): 1, ('absl-py', '0.1.7', 'https://pypi.org/simple'): 1, ('absl-py', '0.1.8', 'https://pypi.org/simple'): 1, ('absl-py', '0.1.9', 'https://pypi.org/simple'): 1, ('absl-py', '0.2.0', 'https://pypi.org/simple'): 1, ('absl-py', '0.2.1', 'https://pypi.org/simple'): 1}
```

**Pull request merged**
