### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by codificat**
## This Pull Request implements

Update the GitHub issue templates using the ones from the template project.

## Description

The main need here was to switch the default issue label to `needs-triage` instead of `triage/needs-information` (the latter is to be added after a review that detects missing information).

Also taking the opportunity to update pre-commit plugins

### CODE REVIEW

**Review by harshad16 — APPROVED** [review]
lgtm
thanks :100:

**Comment by codificat** [comment]
/assign @mayaCostantini 
for approval, thanks.

Note that, in the end, this is removing the `needs-triage` label altogether. Rationale for this in https://github.com/thoth-station/thoth-application/issues/2359#issuecomment-1042832262

**Review by mayaCostantini — APPROVED** [review]
lgtm 👍🏻

**Comment by KPostOffice** [comment]
Hey @codificat are we removing both `needs-triage` and `triage/needs-information` labels?

**Pull request merged**
