### PR TITLE
Remove qeb-hwt integration

### PR DESCRIPTION
**Pull request by pacospace**
Signed-off-by: Francesco Murdaca <fmurdaca@redhat.com>

## Related Issues and Dependencies

Related-To: https://github.com/thoth-station/user-api/issues/1454

### CODE REVIEW

**Comment by KPostOffice** [comment]
Hmm. I worry about how this will change the values of the surrounding enums if we store them anywhere. Can we explicitly set them here so that they don't change?

**Comment by pacospace** [comment]
> Hmm. I worry about how this will change the values of the surrounding enums if we store them anywhere. Can we explicitly set them here so that they don't change?

Sorry I didn't get what needs to be done :) you mean removing auto()?

**Comment by fridex** [comment]
Calls to `auto` make [incremental values for enums](https://docs.python.org/3/library/enum.html#using-automatic-values):

```python
    CLI = auto()                                     # ==1
    KEBECHET = auto()                                # ==2
    S2I = auto()                                     # ==3
    GITHUB_APP = auto()                              # ==4
    JUPYTER_NOTEBOOK = auto()                        # ==5
```

by removing `GITHUB_APP`, `JUPYTER_NOTEBOOK` will be equal to 4. That means any stored values of the enum affected will change semantics.

**Comment by pacospace** [comment]
> Calls to `auto` make [incremental values for enums](https://docs.python.org/3/library/enum.html#using-automatic-values):
> 
> ```python
>     CLI = auto()                                     # ==1
>     KEBECHET = auto()                                # ==2
>     S2I = auto()                                     # ==3
>     GITHUB_APP = auto()                              # ==4
>     JUPYTER_NOTEBOOK = auto()                        # ==5
> ```
> 
> by removing `GITHUB_APP`, `JUPYTER_NOTEBOOK` will be equal to 4. That means any stored values of the enum affected will change semantics.

Thanks @fridex!! so what should we do now? should we move to something like: https://github.com/thoth-station/storages/blob/59168a39eb5480e59d2f095e2e42f69933efd589/thoth/storages/graph/enums.py#L62.

Also why do we have two classes for integrations? One in storages and one in common? should we just keep one to avoid inconsistencies? https://github.com/thoth-station/common/blob/a88ee9b7ccfff937920d9ee4016c58ffbb4eb7a4/thoth/common/enums.py#L23

**Comment by fridex** [comment]
> Also why do we have two classes for integrations? One in storages and one in common? should we just keep one to avoid inconsistencies? https://github.com/thoth-station/common/blob/a88ee9b7ccfff937920d9ee4016c58ffbb4eb7a4/thoth/common/enums.py#L23

That would be great 👍🏻

**Comment by pacospace** [comment]
> > Also why do we have two classes for integrations? One in storages and one in common? should we just keep one to avoid inconsistencies? https://github.com/thoth-station/common/blob/a88ee9b7ccfff937920d9ee4016c58ffbb4eb7a4/thoth/common/enums.py#L23
> 
> That would be great 👍🏻

Then we could keep it in storages I guess as the content is mapped to database in general? wdyt?

**Comment by fridex** [comment]
> > > Also why do we have two classes for integrations? One in storages and one in common? should we just keep one to avoid inconsistencies? https://github.com/thoth-station/common/blob/a88ee9b7ccfff937920d9ee4016c58ffbb4eb7a4/thoth/common/enums.py#L23
> > 
> > 
> > That would be great 👍🏻
> 
> Then we could keep it in storages I guess as the content is mapped to database in general? wdyt?

Given its use in thoth-common, I would say the enum is more suitable to stay in thoth-common and let thoth-storages import it from there.

**Review by KPostOffice — COMMENTED** [review]
/lgtm does this need a new release of thoth-common or is it gtg?

**Pull request merged**
