### PR TITLE
Update lock file to fix issues in CI

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

#1818

## This introduces a breaking change

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by harshad16** [comment]
recheck

**Comment by fridex** [comment]
> Please contact the owners to get included in [CODEOWNERS](https://github.com/thoth-station/storages/blob/master/.github/CODEOWNERS)

Why aren't you mentioned?! :disappointed:

**Comment by harshad16** [comment]
> > Please contact the owners to get included in [CODEOWNERS](https://github.com/thoth-station/storages/blob/master/.github/CODEOWNERS)
> 
> Why aren't you mentioned?!

cant be owner everywhere right :) , need to earn that spot :+1:

**Comment by fridex** [comment]
recheck

**Pull request merged**
