### PR TITLE
Unloop join to index in the unsolved query

### PR DESCRIPTION
**Pull request by fridex**
## This introduces a breaking change

- [x] No

### CODE REVIEW

**Comment by fridex** [comment]
/hold

WIP

**Comment by pacospace** [comment]
@fridex what is the status of this?

**Comment by fridex** [comment]
> @fridex what is the status of this?

/unhold

Ready to be reviewed.

**Review by pacospace — COMMENTED** [review]
lgtm! I did not test them!

**Comment by goern** [comment]
what is the status of this? is it good to go? or to be converted into a draft?

**Review by pacospace — APPROVED** [review]

**Pull request merged**
