### PR TITLE
Introduce Ceph connection check

### PR DESCRIPTION
**Pull request by fridex**

### CODE REVIEW

**Comment by fridex** [comment]
Related: https://github.com/thoth-station/result-api/issues/17

**Comment by goern** [comment]
>/assign @goern 

@fridex if the file is not found that will not raise an exception?!

**Comment by fridex** [comment]
> @fridex if the file is not found that will not raise an exception?!

The `document_exists()` method returns true/false depending on file presence. See comment in the implemented method.

**Pull request merged**
