### PR TITLE
Fix syncing external software environments coming from adviser

### PR DESCRIPTION
**Pull request by fridex**
Fixes: #1450

### CODE REVIEW

**Comment by fridex** [comment]
@pacospace the code is starting to be... ehm... we should refactor some of the parts.

**Comment by fridex** [comment]
Tested locally, works. I will merge this and issue a new release to make pieces moving again in stage env. Feel free to raise any comments.

**Comment by pacospace** [comment]
What do you have in mind? 🙂

**Comment by fridex** [comment]
> What do you have in mind?

Fix typing and some of the methods could be refactored a bit. But nothing big we would need immediately.

**Pull request merged**
