### PR TITLE
Create index for Thoth's s2i base image attributes

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Related: https://github.com/thoth-station/storages/pull/2193

## This introduces a breaking change

- [x ] No

This will improve performance as we add more images.

### CODE REVIEW

**Review by pacospace — COMMENTED** [review]
missing almebic migration?

**Comment by fridex** [comment]
@pacospace Added, PTAL.

**Comment by fridex** [comment]
/approve

The alembic migration added. Merging to continue with the work. Feel free to raise any comments/concerns about this.

**Pull request merged**
