### PR TITLE
Remove bits related to package analyzer

### PR DESCRIPTION
**Pull request by fridex**
## This introduces a breaking change

- [x] No

## This should yield a new module release

- [x] No

## This Pull Request implements

The adapter responsible for package analyses storing is no longer relevant as package-analyzer has been archived.

### CODE REVIEW

**Comment by fridex** [comment]
Generated corresponding migration and rebased. Should be ready to be merged, but will wait for #1958 first.

**Comment by goern** [comment]
ping?!

**Review by pacospace — APPROVED** [review]

**Comment by pacospace** [comment]
rebase @fridex please

**Comment by fridex** [comment]
Closing, replaced with #1994.

**Pull request closed without merging**
